# Please read the comments and configure accordingly; don't just copy this.
version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "dbrootpass" # changeme
      MYSQL_DATABASE: vaultwarden
      MYSQL_USER: vaultuser
      MYSQL_PASSWORD: "vaultpass" # changeme
    volumes:
      - /data/vwsql:/var/lib/mysql


  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: always
    depends_on:
     - mariadb
    volumes:
      - /data/vaultwarden/:/data/
    ports:
      - "777:80" # Use your reverse proxy and connect it to HTTP on port 777 (or any port of your choice). The web interface should only be accessible over HTTPS.
    environment:
      DATABASE_URL: "mysql://vaultuser:vaultpass@mariadb:3306/vaultwarden" # change vaultpass
      ADMIN_TOKEN: "super_long_password_you_should_change" # temp admin token for /admin (configure smtp within the adminpanel 
      TEMPLATES_FOLDER: "data/german/vaultwarden-lang-de-main" # german Email Templates wget https://github.com/kennymc-c/vaultwarden-lang-de/archive/refs/tags/update250125.zip  && unzip main.zip && sudo cp -r /home/vaultwarden/german/ /data/vaultwarden/german (check for updated files https://github.com/kennymc-c/vaultwarden-lang-de/releases ) 
      SIGNUPS_ALLOWED: false
      #SIGNUPS_ALLOWED_DOMAINS: "" # Allow only specific users to sign up when SIGNUPS_ALLOWED is set to true.
      SIGNUPS_DOMAINS_WHITELIST: "yourdomain.tld,your-domain.tld"
      ORG_ATTACHMENT_LIMIT: "10240"
      USER_ATTACHMENT_LIMIT: "10240"
      ORG_CREATION_USERS: "you@yourdomain.tld,orgadmin2@yourdomain.tld"
      DOMAIN: "https://vault.yourdomain.tld"
      #SIGNUPS_VERIFY_RESEND_LIMIT: "6"
